version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - CAP1_CLIENT_ID=\${CAP1_CLIENT_ID}
      - CAP1_CLIENT_SECRET=\${CAP1_CLIENT_SECRET}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
