version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      CAP1_CLIENT_ID: ${CAP1_CLIENT_ID}
      CAP1_CLIENT_SECRET: ${CAP1_CLIENT_SECRET}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE: http://localhost:8080
    depends_on:
      - backend

volumes:
  pgdata:
