# src/main/resources/application.yml
server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          capitalone:
            client-id:     ${CAPI_CLIENT_ID}
            client-secret: ${CAPI_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - accounts
              - transactions
        provider:
          capitalone:
            authorization-uri: https://sandbox.capitalone.io/oauth2/authorize
            token-uri:         https://sandbox.capitalone.io/oauth2/token
            user-info-uri:     https://sandbox.capitalone.io/userinfo
            user-name-attribute: sub

  datasource:
    # now driven by your .env / docker-compose.yml
    url:               ${SPRING_DATASOURCE_URL}
    username:          ${SPRING_DATASOURCE_USERNAME}
    password:          ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect